#!/bin/bash

while read orden
do
    if [[ -n $orden ]] then
        Comando=$(echo $orden| awk '{print $1}')
        Argumentos=$(echo $orden| awk '{for (i=2; i<=NF; ++i)  printf $i " " }') 


        case "$Comando" in
            "enrutar")
                /usr/local/JSBach/scripts/enrutar $Argumentos
                ;;
            "ifwan")
                /usr/local/JSBach/scripts/ifwan $Argumentos
                ;;
            *)
                echo "CLI Error en el argumento"
                ;;
        esac
    fi

    echo "final"
done;

