#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

while read orden
do
    if [[ -n $orden ]] then
        Comando=$(echo $orden| awk '{print $1}')
        Argumentos=$(echo $orden| awk '{for (i=2; i<=NF; ++i)  printf $i " " }') 


        case "$Comando" in
            "enrutar")
                $DIR/$NOMBRE_EQUIPO/$DIR_SCRIPTS/enrutar $Argumentos
                ;;
            "ifwan")
                $DIR/$NOMBRE_EQUIPO/$DIR_SCRIPTS/ifwan $Argumentos
                ;;
            *)
                echo "CLI Error en el argumento"
                ;;
        esac
    fi

    echo "final"
done;

