#!/bin/bash

source /usr/local/JSBach/conf/variables.conf

echo "Content-type: text/html"
echo ""


/bin/cat <<EOM
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hola Mundo CGI</title>
</head>
<body>
  <h1>IFWAN Estado</h1>
EOM

echo "$($DIR/$NOMBRE_EQUIPO/$DIR_SCRIPTS/client_srv_cli ifwan estado) <br>"

/bin/cat <<EOM
</body>
</html>
EOM



