#!/bin/bash

# Cabecera HTTP obligatoria
echo "Content-type: text/html"
echo ""

# Bloque HTML con EOF
/bin/cat <<EOM
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hola Mundo CGI</title>
</head>
<body>
  <h1>IFWAN Estado</h1>
EOM

while IFS= read -r linea
do
    if [[ $linea == 'final' ]]; then
      break
    fi

    echo "$linea"

done < <((echo "enrutar parar") | nc 127.0.0.1 1234)    

/bin/cat <<EOM
</body>
</html>
EOM



