#!/bin/bash

# Cabecera HTTP obligatoria
echo "Content-type: text/html"
echo ""

# Bloque HTML con EOF
/bin/cat <<EOM
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Hola Mundo CGI</title>
</head>
<body>
  <h1>IFWAN Estado</h1>
EOM

echo "$(/usr/local/JSBach/scripts/client_srv_cli ifwan estado) <br>"

/bin/cat <<EOM
</body>
</html>
EOM



